# TCL File Generated by Component Editor 18.1
# Sun Feb 16 11:12:46 CET 2025
# DO NOT MODIFY


# 
# new_component "new_component" v1.0
#  2025.02.16.11:12:46
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module new_component
# 
set_module_property DESCRIPTION ""
set_module_property NAME new_component
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME new_component
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL period_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file period_controller.vhd VHDL PATH ../../hdl/period_controller.vhd TOP_LEVEL_FILE
add_fileset_file irq_selector.vhd VHDL PATH ../../hdl/irq_selector.vhd
add_fileset_file tick_timer.vhd VHDL PATH ../../hdl/tick_timer.vhd


# 
# parameters
# 
add_parameter counter_height INTEGER 4
set_parameter_property counter_height DEFAULT_VALUE 4
set_parameter_property counter_height DISPLAY_NAME counter_height
set_parameter_property counter_height TYPE INTEGER
set_parameter_property counter_height UNITS None
set_parameter_property counter_height HDL_PARAMETER true
add_parameter tick_length INTEGER 25000000
set_parameter_property tick_length DEFAULT_VALUE 25000000
set_parameter_property tick_length DISPLAY_NAME tick_length
set_parameter_property tick_length TYPE INTEGER
set_parameter_property tick_length UNITS None
set_parameter_property tick_length HDL_PARAMETER true
add_parameter per0 INTEGER 1
set_parameter_property per0 DEFAULT_VALUE 1
set_parameter_property per0 DISPLAY_NAME per0
set_parameter_property per0 TYPE INTEGER
set_parameter_property per0 UNITS None
set_parameter_property per0 HDL_PARAMETER true
add_parameter per1 INTEGER 2
set_parameter_property per1 DEFAULT_VALUE 2
set_parameter_property per1 DISPLAY_NAME per1
set_parameter_property per1 TYPE INTEGER
set_parameter_property per1 UNITS None
set_parameter_property per1 HDL_PARAMETER true
add_parameter per2 INTEGER 3
set_parameter_property per2 DEFAULT_VALUE 3
set_parameter_property per2 DISPLAY_NAME per2
set_parameter_property per2 TYPE INTEGER
set_parameter_property per2 UNITS None
set_parameter_property per2 HDL_PARAMETER true
add_parameter per3 INTEGER 4
set_parameter_property per3 DEFAULT_VALUE 4
set_parameter_property per3 DISPLAY_NAME per3
set_parameter_property per3 TYPE INTEGER
set_parameter_property per3 UNITS None
set_parameter_property per3 HDL_PARAMETER true
add_parameter per4 INTEGER 5
set_parameter_property per4 DEFAULT_VALUE 5
set_parameter_property per4 DISPLAY_NAME per4
set_parameter_property per4 TYPE INTEGER
set_parameter_property per4 UNITS None
set_parameter_property per4 HDL_PARAMETER true
add_parameter per5 INTEGER 6
set_parameter_property per5 DEFAULT_VALUE 6
set_parameter_property per5 DISPLAY_NAME per5
set_parameter_property per5 TYPE INTEGER
set_parameter_property per5 UNITS None
set_parameter_property per5 HDL_PARAMETER true
add_parameter per6 INTEGER 7
set_parameter_property per6 DEFAULT_VALUE 7
set_parameter_property per6 DISPLAY_NAME per6
set_parameter_property per6 TYPE INTEGER
set_parameter_property per6 UNITS None
set_parameter_property per6 HDL_PARAMETER true
add_parameter per7 INTEGER 8
set_parameter_property per7 DEFAULT_VALUE 8
set_parameter_property per7 DISPLAY_NAME per7
set_parameter_property per7 TYPE INTEGER
set_parameter_property per7 UNITS None
set_parameter_property per7 HDL_PARAMETER true
add_parameter per8 INTEGER 9
set_parameter_property per8 DEFAULT_VALUE 9
set_parameter_property per8 DISPLAY_NAME per8
set_parameter_property per8 TYPE INTEGER
set_parameter_property per8 UNITS None
set_parameter_property per8 HDL_PARAMETER true
add_parameter per9 INTEGER 10
set_parameter_property per9 DEFAULT_VALUE 10
set_parameter_property per9 DISPLAY_NAME per9
set_parameter_property per9 TYPE INTEGER
set_parameter_property per9 UNITS None
set_parameter_property per9 HDL_PARAMETER true
add_parameter per10 INTEGER 11
set_parameter_property per10 DEFAULT_VALUE 11
set_parameter_property per10 DISPLAY_NAME per10
set_parameter_property per10 TYPE INTEGER
set_parameter_property per10 UNITS None
set_parameter_property per10 HDL_PARAMETER true
add_parameter per11 INTEGER 12
set_parameter_property per11 DEFAULT_VALUE 12
set_parameter_property per11 DISPLAY_NAME per11
set_parameter_property per11 TYPE INTEGER
set_parameter_property per11 UNITS None
set_parameter_property per11 HDL_PARAMETER true
add_parameter per12 INTEGER 13
set_parameter_property per12 DEFAULT_VALUE 13
set_parameter_property per12 DISPLAY_NAME per12
set_parameter_property per12 TYPE INTEGER
set_parameter_property per12 UNITS None
set_parameter_property per12 HDL_PARAMETER true
add_parameter per13 INTEGER 14
set_parameter_property per13 DEFAULT_VALUE 14
set_parameter_property per13 DISPLAY_NAME per13
set_parameter_property per13 TYPE INTEGER
set_parameter_property per13 UNITS None
set_parameter_property per13 HDL_PARAMETER true
add_parameter per14 INTEGER 15
set_parameter_property per14 DEFAULT_VALUE 15
set_parameter_property per14 DISPLAY_NAME per14
set_parameter_property per14 TYPE INTEGER
set_parameter_property per14 UNITS None
set_parameter_property per14 HDL_PARAMETER true
add_parameter per15 INTEGER 16
set_parameter_property per15 DEFAULT_VALUE 16
set_parameter_property per15 DISPLAY_NAME per15
set_parameter_property per15 TYPE INTEGER
set_parameter_property per15 UNITS None
set_parameter_property per15 HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset ""
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 p0_irq_out writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 cs_n beginbursttransfer Input 1
add_interface_port avalon_slave_0 addr writebyteenable_n Input 2
add_interface_port avalon_slave_0 write_n write_n Input 1
add_interface_port avalon_slave_0 read_n read_n Input 1
add_interface_port avalon_slave_0 din writebyteenable_n Input 32
add_interface_port avalon_slave_0 dout readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end conduit_end_new_signal new_signal Output 1

