# TCL File Generated by Component Editor 22.1
# Wed Nov 22 12:53:10 CET 2023
# DO NOT MODIFY


# 
# timer_hw_ip "timer_hw_ip" v0.0.1
# IP 2023.11.22.12:53:10
# Timer counting clk periods
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module agstu_hw_timer
# 
set_module_property DESCRIPTION "Timer counting clk periods"
set_module_property NAME agstu_hw_timer
set_module_property VERSION 0.0.2
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP MyGroup
set_module_property AUTHOR IP
set_module_property DISPLAY_NAME agstu_hw_timer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL TIMER_HW_IP
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file TIMER_HW_IP.vhd VHDL PATH hdl/TIMER_HW_IP.vhd TOP_LEVEL_FILE
add_fileset_file timer_function.vhd VHDL PATH hdl/timer_function.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock ""
set_interface_property reset synchronousEdges NONE
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point timer_hw_data
# 
add_interface timer_hw_data avalon end
set_interface_property timer_hw_data addressUnits WORDS
set_interface_property timer_hw_data associatedClock clock
set_interface_property timer_hw_data associatedReset reset
set_interface_property timer_hw_data bitsPerSymbol 8
set_interface_property timer_hw_data burstOnBurstBoundariesOnly false
set_interface_property timer_hw_data burstcountUnits WORDS
set_interface_property timer_hw_data explicitAddressSpan 0
set_interface_property timer_hw_data holdTime 0
set_interface_property timer_hw_data linewrapBursts false
set_interface_property timer_hw_data maximumPendingReadTransactions 0
set_interface_property timer_hw_data maximumPendingWriteTransactions 0
set_interface_property timer_hw_data readLatency 0
set_interface_property timer_hw_data readWaitTime 1
set_interface_property timer_hw_data setupTime 0
set_interface_property timer_hw_data timingUnits Cycles
set_interface_property timer_hw_data writeWaitTime 0
set_interface_property timer_hw_data ENABLED true
set_interface_property timer_hw_data EXPORT_OF ""
set_interface_property timer_hw_data PORT_NAME_MAP ""
set_interface_property timer_hw_data CMSIS_SVD_VARIABLES ""
set_interface_property timer_hw_data SVD_ADDRESS_GROUP ""

add_interface_port timer_hw_data cs_n chipselect_n Input 1
add_interface_port timer_hw_data addr address Input 2
add_interface_port timer_hw_data write_n write_n Input 1
add_interface_port timer_hw_data read_n read_n Input 1
add_interface_port timer_hw_data din writedata Input 32
add_interface_port timer_hw_data dout readdata Output 32
set_interface_assignment timer_hw_data embeddedsw.configuration.isFlash 0
set_interface_assignment timer_hw_data embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment timer_hw_data embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment timer_hw_data embeddedsw.configuration.isPrintableDevice 0

